server:
  port: ${PORT:8080}
  servlet:
    context-path: "/quotes"

spring:
  application:
    name: quotes-service
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: "jdbc:postgresql://ec2-63-33-14-215.eu-west-1.compute.amazonaws.com/de9b5qj94rkfii"
    username: "zajprpfudsqjul"
    password: "3e8278bb2f7bd9526abe49b03a3665fa128b20d5b5615cdcbb23310a49a25f73"