server:
  port: 8080
  servlet:
    context-path: "/quotes"

spring:
  application:
    name: quotes-service
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/quotes"
    username: "postgres"
    password: "postgres"